# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'edit_profile.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from restaurant_db import * 


class Ui_editMainWindow(object):
    def setupUi(self, MainWindow, restaurant_id):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(862, 594)
        self.edit_profile_widget = QtWidgets.QWidget(MainWindow)
        self.edit_profile_widget.setStyleSheet("*{\n"
"    color :#f7c55d;\n"
"    }\n"
"#edit_profile_widget{\n"
"    background-color: #0f0f0f;\n"
"    }\n"
"\n"
"#profileframe {\n"
"    background-color : #292929;\n"
"    }\n"
"\n"
"#submit_btn_frame {\n"
"    background-color :#f7c55d;\n"
"    border-radius : 10px;\n"
"    }\n"
"#submit_btn{\n"
"    background-color :#f7c55d;\n"
"    color :#292929;\n"
"    border :none;\n"
"    }\n"
"#first_name_input , #last_name_input, #phonenumber_input, #email_input, #id_number_input, #password_input, #picture_path_input{\n"
"    background-color : #292929;\n"
"\n"
"    }\n"
"    ")
        self.restaurant_id = restaurant_id
        self.edit_profile_widget.setObjectName("edit_profile_widget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.edit_profile_widget)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.profileframe = QtWidgets.QFrame(self.edit_profile_widget)
        self.profileframe.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.profileframe.setFrameShadow(QtWidgets.QFrame.Raised)
        self.profileframe.setObjectName("profileframe")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.profileframe)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.infoframe = QtWidgets.QFrame(self.profileframe)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.infoframe.sizePolicy().hasHeightForWidth())
        self.infoframe.setSizePolicy(sizePolicy)
        self.infoframe.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.infoframe.setFrameShadow(QtWidgets.QFrame.Raised)
        self.infoframe.setObjectName("infoframe")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.infoframe)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.name_frame = QtWidgets.QFrame(self.infoframe)
        self.name_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.name_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.name_frame.setObjectName("name_frame")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.name_frame)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label = QtWidgets.QLabel(self.name_frame)
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.horizontalLayout_2.addWidget(self.label, 0, QtCore.Qt.AlignLeft)
        self.first_name_input = QtWidgets.QLineEdit(self.name_frame)
        font = QtGui.QFont()
        font.setPointSize(13)
        self.first_name_input.setFont(font)
        self.first_name_input.setText("")
        self.first_name_input.setObjectName("first_name_input")
        self.horizontalLayout_2.addWidget(self.first_name_input)
        self.verticalLayout_5.addWidget(self.name_frame)
        self.frame = QtWidgets.QFrame(self.infoframe)
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.frame)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.label_6 = QtWidgets.QLabel(self.frame)
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.horizontalLayout_6.addWidget(self.label_6)
        self.last_name_input = QtWidgets.QLineEdit(self.frame)
        font = QtGui.QFont()
        font.setPointSize(13)
        self.last_name_input.setFont(font)
        self.last_name_input.setText("")
        self.last_name_input.setObjectName("last_name_input")
        self.horizontalLayout_6.addWidget(self.last_name_input)
        self.verticalLayout_5.addWidget(self.frame)
        self.frame_2 = QtWidgets.QFrame(self.infoframe)
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.frame_2)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_2 = QtWidgets.QLabel(self.frame_2)
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_3.addWidget(self.label_2)
        self.phonenumber_input = QtWidgets.QLineEdit(self.frame_2)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.phonenumber_input.setFont(font)
        self.phonenumber_input.setText("")
        self.phonenumber_input.setObjectName("phonenumber_input")
        self.horizontalLayout_3.addWidget(self.phonenumber_input)
        self.verticalLayout_5.addWidget(self.frame_2)
        self.frame_3 = QtWidgets.QFrame(self.infoframe)
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.frame_3)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_3 = QtWidgets.QLabel(self.frame_3)
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_4.addWidget(self.label_3)
        self.email_input = QtWidgets.QLineEdit(self.frame_3)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.email_input.setFont(font)
        self.email_input.setText("")
        self.email_input.setObjectName("email_input")
        self.horizontalLayout_4.addWidget(self.email_input)
        self.verticalLayout_5.addWidget(self.frame_3)
        self.frame_6 = QtWidgets.QFrame(self.infoframe)
        self.frame_6.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_6.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_6.setObjectName("frame_6")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout(self.frame_6)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.label_10 = QtWidgets.QLabel(self.frame_6)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_10.setFont(font)
        self.label_10.setObjectName("label_10")
        self.horizontalLayout_7.addWidget(self.label_10)
        self.picture_path_input = QtWidgets.QLineEdit(self.frame_6)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.picture_path_input.setFont(font)
        self.picture_path_input.setObjectName("picture_path_input")
        self.horizontalLayout_7.addWidget(self.picture_path_input)
        self.verticalLayout_5.addWidget(self.frame_6)
        self.submit_btn_frame = QtWidgets.QFrame(self.infoframe)
        self.submit_btn_frame.setStyleSheet("background-color: none;")
        self.submit_btn_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.submit_btn_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.submit_btn_frame.setObjectName("submit_btn_frame")
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout(self.submit_btn_frame)
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.submit_btn = QtWidgets.QPushButton(self.submit_btn_frame)
        self.submit_btn.setStyleSheet("height: 45px;\n"
"background-color: #f7c55d;\n"
"border-radius: 10px\n"
"")
        self.submit_btn.setObjectName("submit_btn")
        self.horizontalLayout_9.addWidget(self.submit_btn)
        self.verticalLayout_5.addWidget(self.submit_btn_frame)
        self.verticalLayout_2.addWidget(self.infoframe)
        self.err_label = QtWidgets.QLabel(self.profileframe)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.err_label.setFont(font)
        self.err_label.setStyleSheet("color: #F94C66;")
        self.err_label.setText("")
        self.err_label.setObjectName("err_label")
        self.verticalLayout_2.addWidget(self.err_label)
        self.horizontalLayout.addWidget(self.profileframe)
        MainWindow.setCentralWidget(self.edit_profile_widget)

        val = (self.restaurant_id,)
        sql = "SELECT * FROM restuarantinfo WHERE restuarant_id = %s"
        mycursor.execute(sql, val)
        myresult = mycursor.fetchall() # get data from database 
        for info in myresult:
            # give a default text to line edites 
            self.first_name_input.setText(info[2])
            self.last_name_input.setText(info[3])
            self.phonenumber_input.setText(info[4])
            self.email_input.setText(info[5])

        self.submit_btn.clicked.connect(self.edit_restaurtant_info)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def edit_restaurtant_info(self):
        """change database values by clicking on button"""
        if self.first_name_input.text().strip() != '' and self.last_name_input.text().strip() != '' and self.phonenumber_input.text().strip() != '' and self.email_input.text().strip() != '': 
            sql = "UPDATE restuarantinfo SET restaurant_name = %s, restaurant_district = %s, restuarant_catagory = %s, restuarant_address = %s WHERE manager_id = %s"
            val = (self.first_name_input.text(), self.last_name_input.text(), self.phonenumber_input.text(), self.email_input.text(), self.restaurant_id)
            mycursor.execute(sql, val)
            mydb.commit()
            self.edit_profile_widget.close()
        else:
            self.err_label.setText("error: you should fill all the inputs!!!")
    
    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "restaurant name:"))
        self.label_6.setText(_translate("MainWindow", "district: "))
        self.label_2.setText(_translate("MainWindow", "catagory: "))
        self.label_3.setText(_translate("MainWindow", "address: "))
        self.label_10.setText(_translate("MainWindow", "Picture Path : "))
        self.picture_path_input.setText(_translate("MainWindow", "D:\\projects\\FPAP\\profilepicture.png"))
        self.submit_btn.setText(_translate("MainWindow", "Submit"))
